# DeluxeChat version 1.16.2 config file
# Created by extended_clip
# List as many format configurations you in the formats: config section.
# Each format configuration requires a specific layout which can be seen below.
# Format priority must be specified per format and each priority must be unique.
# higher value = lower priority
# ex: guest-100, owner-1
#   YOU MUST KEEP A 'default' TEMPLATE! 
#   
# Social Spy only allows %player% and %recipient% as placeholders
# 
# You must download the placeholder expansion through PlaceholderAPI for which
# placeholders you want to use. The example below uses Player placeholders, so
# we need to download the player expansion: /papi ecloud download Player, /papi reload
# 
# 
# example format template:
# formats: 
#   default:
#     priority: 2147483647
#     channel: ''
#     prefix: '&8[&7Guest&8] '
#     name_color: '&7'
#     name: '%player_name%'
#     suffix: '&7> '
#     chat_color: '&f'
#     channel_tooltip:
#     - '&7%player_name% &bis a Guest'
#     prefix_tooltip:
#     - '&7%player_name% &bis a Guest'
#     name_tooltip:
#     - ''
#     suffix_tooltip:
#     - ''
#     channel_click_command: '
#     prefix_click_command: '/ranks
#     name_click_command: '/msg %player_name% 
#     suffix_click_command: '
#   Member:
#     priority: 100
#     channel: ''
#     prefix: '&8[&aMember&8] '
#     name_color: '&7'
#     name: '%player_name%'
#     suffix: '&7> '
#     chat_color: '&f'
#     channel_tooltip:
#     - '&7%player_name% &bis a Member'
#     prefix_tooltip:
#     - '&7%player_name% &bis a Member'
#     name_tooltip:
#     - ''
#     suffix_tooltip:
#     - ''
#     channel_click_command: '
#     prefix_click_command: '/ranks
#     name_click_command: '/msg %player_name% 
#     suffix_click_command: '
check_updates: true
bungeecord:
  enabled: false
  server_name: Server
  server_prefix: '&8[&cServer&8]'
  join_global: true
  use_server_whitelist: true
  server_whitelist:
  - Server2
  - Server3
relation_placeholders_enabled: true
timestamp_format: MM/dd/yy HH:mm:ss
boolean:
  'true': '&atrue'
  'false': '&cfalse'
ops_use_group_format: false
chat_filter:
  enabled: true
  ignore_case: true
  list:
  - '.; '
  - fuck;fuck
  - play.
  - mc.
  - join.
  - mc.plaay.com
  - .com
  - .net
  - .org
  - .us
  - .es
  - play.server.net
  - mc.server.net
  - play.d
  - play.server.ml
  - mc.server.org
  - .tk
  - .ml
  - mc.server.tk
  - mc.server.com
  - play.server.com
  - mc.server
  - play.lightersmc.net
  - play.server.org
  - mc.server.ml
  - craft
  - mc
  - play.server
private_message:
  enabled: false
  bungeecord: false
private_message_formats:
  to_sender:
    format: '&7you &e-> &7%recipient_player_name% &7:'
    tooltip:
    - '%player_name%'
    click_command: '/r '
    chat_color: '&3'
  to_recipient:
    format: '&7%player_name% &e-> &7you &7:'
    tooltip:
    - '%player_name%'
    click_command: '/r '
    chat_color: '&3'
  social_spy: '&8[&cspy&8] &f%player% &e-> &f%recipient%&7:'
formats:
  default:
    priority: 2147483647
    channel: ''
    prefix: '&7[%vault_group%&7] '
    name_color: '&b'
    name: '%player_name%'
    suffix: '&7> '
    chat_color: '&f'
    channel_tooltip:
    - ''
    prefix_tooltip:
    - '%player_name%'
    - '&bRank: %vault_group%'
    name_tooltip:
    - ''
    suffix_tooltip:
    - ''
    channel_click_command: /ranks
    prefix_click_command: /ranks
    name_click_command: '/msg %player_name% '
    suffix_click_command: ''
  general:
    priority: 2147483647
    channel: ''
    prefix: '%kitbattle_player_rank_prefix% %vault_rankprefix%'
    name_color: '&7'
    name: '%essentials_nickname%'
    suffix: '&f%vault_suffix% &8» '
    chat_color: '&f'
    channel_tooltip:
    - ''
    prefix_tooltip:
    - '&a「 &a&lPERFIL &a| &a%player_name% 」'
    - ''
    - '&8|&e &fRango: &b%kitbattle_player_rank%'
    - '&8|&e &fMonedas: &e$%vault_eco_balance_formatted%'
    - ''
    - '&8|&e &fEXP: &b%kitbattle_player_exp%/%kitbattle_player_next_rank_exp%'
    - ''
    - '&8|&e &fAsesinatos: &c%kitbattle_kills%'
    - '&8|&e &fMuertes: &e%kitbattle_deaths%'
    - ''
    - '&d     &dKarmancos'
    name_tooltip:
    - '&a「 &a&lPERFIL &a| &a%player_name% 」'
    - ''
    - '&8|&e &fRango: &b%kitbattle_player_rank%'
    - '&8|&e &fMonedas: &e$%vault_eco_balance_formatted%'
    - ''
    - '&8|&e &fEXP: &b%kitbattle_player_exp%/%kitbattle_player_next_rank_exp%'
    - ''
    - '&8|&e &fAsesinatos: &c%kitbattle_kills%'
    - '&8|&e &fMuertes: &e%kitbattle_deaths%'
    - ''
    - '&d     &dkarmancos'
    channel_click_command: '/msg %player_name% '
    prefix_click_command: '/msg %player_name% '
    name_click_command: '/msg %player_name% '
    suffix_click_command: '/msg %player_name% '
